version: '2'
services:
  hubot:
    image: kylev/hubot
    command: -a slack
    environment:
      HUBOT_SLACK_TOKEN: xoxb-302399241078-937815978871-yFEYnjG2PTmcChjvOLj0QDiZ
    volumes:
      - .:/hubot